name: Black

on:
  - push
  - pull_request

jobs:
  black:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Python version
        run: python --version
      - name: PDM installation
        run: pip install --user pdm
      - name: Install devel dependencies
        run: pdm install --dev
      - name: Black version
        run: pdm run black --version
      - name: Black check
        run: pdm run black . --check
